# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          ZeroFOX Engineering
paginate:       5
baseurl:        ""
url:            "https://github.com/zerofox-oss"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
